# Generated by Django 4.1 on 2022-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=120000, verbose_name='Цена комнаты'),
            preserve_default=False,
        ),
    ]
