# Generated by Django 4.1 on 2022-08-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(verbose_name='Занято с')),
                ('date_out', models.DateField(verbose_name='Занято по')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.rooms')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
    ]
