# Generated by Django 4.1 on 2022-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_reserve_options_rooms_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='date_end',
            field=models.DateField(blank=True, verbose_name='Занято по'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='date_start',
            field=models.DateField(blank=True, verbose_name='Занято с'),
        ),
    ]
