# Generated by Django 3.2.15 on 2022-09-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_rooms_date_end_alter_rooms_date_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
