# Generated by Django 3.2.15 on 2022-09-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
        ('rooms', '0006_delete_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='photo',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo'),
        ),
    ]
