# Generated by Django 3.2.15 on 2022-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220917_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='image',
            new_name='photo',
        ),
    ]
