# Generated by Django 3.2.15 on 2022-09-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_rename_image_rooms_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
