# Generated by Django 3.2.15 on 2022-09-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_auto_20220917_2215'),
        ('rooms', '0009_alter_rooms_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo'),
        ),
    ]
